import os
ali=os.getcwd() # cwd ka matlab khai current direcitey
print(ali)
os.chdir("C:\\New folder (2)")
print(os.getcwd())

print(os.listdir())
#os.mkdir("musakhan")
print (os.listdir())
#os.rmdir("musakhan")
print(os.listdir())
#os.rename("musakhan","musakhan.txt")
print(os.listdir())
#y=os.path.exists("musakhan.txt")
#print(y)
path=os.path.join(r"c:\Desktop\python_automation\python_auto1.py")
print(path)
print(os.path.abspath("musakhan.txt"))
print(os.path.getsize("musakhan.txt"))
print(os.environ)
y=os.system("ipconfig")
print(y)
target=input("inter targeted ip " )
os.system(f'ping {target}')